# Generated by Django 5.2.4 on 2025-09-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_alter_lecture_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
