# Generated by Django 5.2.4 on 2025-09-22 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecture_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='instructor',
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='lectures_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
