# Generated by Django 5.2.4 on 2025-09-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('program', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exams')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtables', to='faculty.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtables', to='program.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtables', to='university.university')),
            ],
        ),
    ]
