# Generated by Django 5.2.3 on 2025-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtable',
            name='level',
            field=models.CharField(blank=True, choices=[('المستوى الأول', 'المستوى الأول'), ('المستوى الثاني', 'المستوى الثاني'), ('المستوى الثالث', 'المستوى الثالث'), ('المستوى الرابع', 'المستوى الرابع'), ('المستوى الخامس', 'المستوى الخامس'), ('المستوى السادس', 'المستوى السادس'), ('المستوى السابع', 'المستوى السابع')], max_length=20, null=True),
        ),
    ]
