# Generated by Django 5.2.4 on 2025-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('المستوى الأول', 'المستوى الأول'), ('المستوى الثاني', 'المستوى الثاني'), ('المستوى الثالث', 'المستوى الثالث'), ('المستوى الرابع', 'المستوى الرابع'), ('المستوى الخامس', 'المستوى الخامس')], max_length=20, null=True),
        ),
    ]
