# Generated by Django 5.2.4 on 2025-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('المستوى الأول', 'المستوى الأول'), ('المستوى الثاني', 'المستوى الثاني'), ('المستوى الثالث', 'المستوى الثالث'), ('المستوى الرابع', 'المستوى الرابع'), ('المستوى الخامس', 'المستوى الخامس'), ('المستوى السادس', 'المستوى السادس'), ('المستوى السابع', 'المستوى السابع')], max_length=20, null=True),
        ),
    ]
