# Generated by Django 5.2.4 on 2025-09-17 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0003_alter_lecture_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('ممتاز', 'ممتاز'), ('جيد جدا', 'جيد جدا'), ('جيد', 'جيد'), ('مقبول', 'مقبول'), ('ضعيف', 'ضعيف')])),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='lecture.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='survey.surveyquestion')),
            ],
            options={
                'unique_together': {('lecture', 'question', 'student')},
            },
        ),
    ]
