# Generated by Django 5.2.3 on 2025-09-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='scan_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.CreateModel(
            name='AttendanceQRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='attendance.attendance')),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'attendance'], name='attendance__token_3900ed_idx'), models.Index(fields=['expires_at'], name='attendance__expires_0cac84_idx')],
            },
        ),
    ]
