# Generated by Django 5.2.4 on 2025-09-20 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance'),
        ('lecture', '0004_lecture_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_mark', models.FloatField(default=0.0)),
                ('instructor_mark', models.FloatField(default=0.0)),
                ('final_mark', models.FloatField(default=0.0, editable=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='lecture.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lecture')},
            },
        ),
    ]
