# Generated by Django 5.2.3 on 2025-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
