"""
Django settings for edu_track project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-92(_qr_dpj84=19ady_i!h$%)df6uoa0d7yqh_6xy2^+d4lgd%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Mobile testing changing depends on the ip of the pc
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
# if DEBUG:
#     ALLOWED_HOSTS = ["*"]

# # Configure Django to bind to all interfaces by default for development
# import os
# if DEBUG:
#     # Override the default runserver command to bind to all interfaces
#     os.environ.setdefault('DJANGO_SERVER_HOST', '0.0.0.0')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'djoser',
    'corsheaders',
    'user.apps.UserConfig',    
    'university.apps.UniversityConfig',
    'faculty.apps.FacultyConfig',
    'program.apps.ProgramConfig',
    'location.apps.LocationConfig',
    'course.apps.CourseConfig',
    'lecture.apps.LectureConfig',
    'attendance.apps.AttendanceConfig',
    'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edu_track.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edu_track.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings created by us

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = 'user.User'

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
}

# DJOSER Configuration - Fixed for proper password reset links
DJOSER = {
    'LOGIN_FIELD': 'username',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    'SEND_ACTIVATION_EMAIL': True,
    'ACTIVATION_URL': 'activation/{uid}-{token}',
    'SEND_CONFIRMATION_EMAIL': True,   
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True, 
    'PASSWORD_RESET_CONFIRM_URL': 'resetpassword/{uid}-{token}', 
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True, 
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    # Fix for proper domain in emails
    'DOMAIN': 'localhost:5173',  # Your frontend domain
    'SITE_NAME': 'EduTrack',
    'PROTOCOL': 'http',  # Change to 'https' in production
    'SERIALIZERS': {
        "user": "user.serializers.UserSerializer",
        "current_user": "user.serializers.UserSerializer",
    },
    'EMAIL': {
        'password_reset': 'djoser.email.PasswordResetEmail',
        'password_changed_confirmation': 'djoser.email.PasswordChangedConfirmationEmail',
        'activation': 'djoser.email.ActivationEmail',
    },
}

# Django Sites Framework - IMPORTANT: This controls the domain in emails
# Note: You need to update the Site domain manually using Django shell or management command
# See instructions below the settings file

# Allow localhost and common LAN IP ranges for development preview
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # Mobile testing changing depends on the ip of the pc
    # "http://192.168.1.7:5173",
    # "http://192.168.1.7:8000",
]

# During development, allow any origin from the local network when DEBUG
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Allow Authorization header without cookies; enable credentials only if needed
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alaaelgharably1@gmail.com'
EMAIL_HOST_PASSWORD = 'lmos nsjm fbau yfsn'  # Consider using environment variables
DEFAULT_FROM_EMAIL = 'admin@edutrack.com'