# Generated by Django 5.2.4 on 2025-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('location', '0002_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='faculty',
        ),
        migrations.AddField(
            model_name='location',
            name='faculties',
            field=models.ManyToManyField(related_name='locations', to='faculty.faculty'),
        ),
    ]
